name: cron by github actions
on: push
jobs:
  dockerhub:
    name: docker pull my images
    runs-on: ubuntu-latest
    steps:
      - name: docker pull
        run: |
          docker pull -a kirasoa/yasc
          docker pull -a kirasoa/cloudera-altuscli
